theme: jekyll-theme-cayman
emptyArray: []

comments:
  receiver: https://{{mo7perez.github.io}}
  defaults:
    -
      scope:
       path: ''
       type: pages
      values:
        layout: page
        author: mo7perez
        commenting: open
     -
       scope:
        path: '_post'
        type: posts
       values: 
        layout: post
        author: mo7perez
        commenting: open
        
       
       
